export const Models = {
  Restaurant: 'restaurants',
  User: 'users',
  Order: 'orders',
  Product: 'products',
  Address: 'addresses',
  Promotion: 'promotions',
  Session: 'sessions',
  Employee: 'employees',
  Category: 'categories',
  Delivery: 'deliveries',
  Chat: 'chats',
  Tracker: 'trackers',
  Menu: 'menus',
  Customer: 'customers',
};
