version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: esgiking_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  # express:
  #   image: mongo-express:latest
  #   container_name: esgiking_express
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - mongo
  #   environment:
  #     MONGO_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/esgiking?authSource=admin
  #   links:
  #     - mongo

volumes:
  mongo_data: