volumes:
   mongo_data:
services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: esgiking_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PWD}
    ports:
      - '27017:27017'
    networks:
      - app-network

  express:
    image: mongo-express:latest
    restart: always
    container_name: esgiking_express
    ports:
      - '8081:8080'
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PWD}
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin

networks:
  app-network:
    driver: bridge

  # api:
  #   build: .
  #   restart: always
  #   depends_on:
  #     - mongo
  #   ports:
  #     - 8080:3000
  #   env_file:
  #     - ".env"
