export * from './user.interface';
export * from './restaurant.interface';
export * from './timestamp.interface';
export * from './order.interface';
export * from './product.interface';
export * from './address.interface';
export * from './promotion.interface';
export * from './session.interface';
export * from './menu.interface';